// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMP_nrD9hakfoZzRsb6e-ChfAFOhjjflI',
    appId: '1:1020191933837:web:54843d247eafdf7c3b69c4',
    messagingSenderId: '1020191933837',
    projectId: 'flutter-unpam',
    authDomain: 'flutter-unpam.firebaseapp.com',
    storageBucket: 'flutter-unpam.firebasestorage.app',
    measurementId: 'G-9VZKR86WKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdFMrqvZlj5jm5FQu37osOtzLxb9v2tA',
    appId: '1:1020191933837:android:062855ce9083e0433b69c4',
    messagingSenderId: '1020191933837',
    projectId: 'flutter-unpam',
    storageBucket: 'flutter-unpam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp-wt24vZpdIAFxctYK81bsiT5U37s00I',
    appId: '1:1020191933837:ios:3521379411843a8f3b69c4',
    messagingSenderId: '1020191933837',
    projectId: 'flutter-unpam',
    storageBucket: 'flutter-unpam.firebasestorage.app',
    iosBundleId: 'com.example.flutterUnpam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp-wt24vZpdIAFxctYK81bsiT5U37s00I',
    appId: '1:1020191933837:ios:3521379411843a8f3b69c4',
    messagingSenderId: '1020191933837',
    projectId: 'flutter-unpam',
    storageBucket: 'flutter-unpam.firebasestorage.app',
    iosBundleId: 'com.example.flutterUnpam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMP_nrD9hakfoZzRsb6e-ChfAFOhjjflI',
    appId: '1:1020191933837:web:b8cd2005567978863b69c4',
    messagingSenderId: '1020191933837',
    projectId: 'flutter-unpam',
    authDomain: 'flutter-unpam.firebaseapp.com',
    storageBucket: 'flutter-unpam.firebasestorage.app',
    measurementId: 'G-KRLSJ00KTB',
  );
}
